"use client";

import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, FileSpreadsheet, Loader2, RotateCcw, Sheet, UploadCloud } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BRAND_NAME } from "@/config/brand";

const steps = ["Upload", "Map columns", "Validation", "Complete"];
const mappings = [
  ["ФИО", "Full name", "Ivan Petrov"], ["Рабочий email", "Email", "ivan@lexbridge.example"], ["Компания", "Company", "Lexbridge Legal"], ["Должность", "Role", "Senior Partner"], ["Город", "City", "Moscow"], ["Категория", "Category", "Lawyer"],
];

export function ImportWizard() {
  const [step,setStep]=useState(0);
  const [file,setFile]=useState("legal-network-august.xlsx");
  const [validating,setValidating]=useState(false);
  const [progress,setProgress]=useState(0);
  const [sheetConnected,setSheetConnected]=useState(false);

  useEffect(()=>{if(!validating)return;const timer=window.setInterval(()=>setProgress(current=>{if(current>=100){window.clearInterval(timer);setValidating(false);return 100}return Math.min(100,current+8)}),90);return()=>window.clearInterval(timer)},[validating]);
  const next=()=>{if(step===1){setStep(2);setProgress(0);setValidating(true)}else setStep(current=>Math.min(3,current+1))};

  return <div className="mx-auto max-w-[980px] space-y-6">
    <div><p className="section-eyebrow">Bring your data</p><h1 className="mt-2 text-[28px] font-medium tracking-[-.04em]">Import contacts</h1><p className="mt-1.5 text-sm text-[var(--text-secondary)]">Add people from a spreadsheet and map them into your workspace.</p></div>
    <div className="card px-4 py-5 sm:px-8"><ol className="relative mx-auto flex max-w-[700px] items-start justify-between before:absolute before:left-[7%] before:right-[7%] before:top-4 before:h-px before:bg-[var(--border)]" aria-label="Import progress">{steps.map((label,index)=><li key={label} aria-current={index===step?"step":undefined} className="relative z-[1] flex w-24 flex-col items-center text-center"><span className={`grid size-8 place-items-center rounded-full border text-[10px] font-semibold transition-colors ${index<step?"border-[#625cf6] bg-[#625cf6] text-white":index===step?"border-[#625cf6] bg-white text-[#625cf6] shadow-[0_0_0_4px_rgba(98,92,246,.1)]":"border-[var(--border-strong)] bg-white text-[var(--text-tertiary)]"}`}>{index<step?<><Check size={13} strokeWidth={3}/><span className="sr-only">Complete</span></>:index+1}</span><span className={`mt-2 text-[9px] font-semibold ${index<=step?"text-[var(--text-primary)]":"text-[var(--text-tertiary)]"}`}>{label}</span></li>)}</ol></div>

    <section className="card min-h-[500px] overflow-hidden">
      {step===0&&<div className="p-5 sm:p-8"><div className="text-center"><h2 className="text-[18px] font-semibold tracking-[-.025em]">Upload your contact file</h2><p className="mt-2 text-[11px] text-[var(--text-tertiary)]">We’ll preview the data before anything is added.</p></div><label className="mx-auto mt-7 flex max-w-[720px] cursor-pointer flex-col items-center rounded-2xl border border-dashed border-[#cfd0db] bg-[#fafafd] px-6 py-12 text-center transition-colors hover:border-[#8a84f8] hover:bg-[#f8f7ff]"><input type="file" className="sr-only" accept=".csv,.xlsx,.xls" onChange={event=>event.target.files?.[0]&&setFile(event.target.files[0].name)}/><span className="grid size-12 place-items-center rounded-2xl bg-[#eeedff] text-[#625cf6]"><UploadCloud size={21}/></span><p className="mt-4 text-[12px] font-semibold">Drop a CSV or XLSX file here</p><p className="mt-1 text-[10px] text-[var(--text-tertiary)]">or click to browse · up to 25 MB</p>{file&&<div className="mt-5 flex items-center gap-3 rounded-xl border border-[#dcddf5] bg-white px-4 py-3 text-left shadow-sm"><span className="grid size-8 place-items-center rounded-lg bg-[#edf8f1] text-[#3e8d5c]"><FileSpreadsheet size={15}/></span><div><p className="text-[10px] font-semibold">{file}</p><p className="mt-0.5 text-[8px] text-[var(--text-tertiary)]">4,821 rows · 1.8 MB</p></div><CheckCircle2 size={15} className="ml-4 text-[#3e8d5c]"/></div>}</label><div className="mx-auto mt-5 flex max-w-[720px] items-center gap-3 text-[9px] uppercase tracking-[.08em] text-[var(--text-tertiary)] before:h-px before:flex-1 before:bg-[var(--border)] after:h-px after:flex-1 after:bg-[var(--border)]">or import from</div><button onClick={()=>{setSheetConnected(true);setFile("Legal Network · Google Sheets")}} className="mx-auto mt-5 flex w-full max-w-[720px] items-center justify-center gap-3 rounded-xl border border-[var(--border)] bg-white py-3 text-[11px] font-semibold hover:bg-[var(--surface-subtle)]"><span className="grid size-7 place-items-center rounded-lg bg-[#eaf8ef] text-[#2d9a58]"><Sheet size={14}/></span>{sheetConnected?"Google Sheet connected":"Connect Google Sheets"}{sheetConnected&&<CheckCircle2 size={14} className="text-[#3e8d5c]"/>}</button></div>}

      {step===1&&<div><div className="border-b border-[var(--border)] px-5 py-5 sm:px-8"><h2 className="text-[18px] font-semibold tracking-[-.025em]">Map your columns</h2><p className="mt-1.5 text-[11px] text-[var(--text-tertiary)]">Tell {BRAND_NAME} where each field belongs. We matched six automatically.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="bg-[var(--surface-subtle)] text-[9px] font-semibold uppercase tracking-[.07em] text-[var(--text-tertiary)]"><th className="px-6 py-3">Uploaded column</th><th className="px-4 py-3">Contact field</th><th className="px-4 py-3">Example value</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{mappings.map(([source,target,example])=><tr key={source} className="border-t border-[var(--border)]"><td className="px-6 py-3.5 text-[10px] font-semibold">{source}</td><td className="px-4 py-3.5"><button className="flex w-full max-w-[210px] items-center justify-between rounded-lg border border-[var(--border)] bg-white px-3 py-2 text-[10px] font-medium">{target}<ChevronDown size={12} className="text-[var(--text-tertiary)]"/></button></td><td className="px-4 py-3.5 text-[9px] text-[var(--text-tertiary)]">{example}</td><td className="px-4 py-3.5"><span className="badge badge-success"><Check size={9}/>Matched</span></td></tr>)}</tbody></table></div><div className="mx-5 my-5 rounded-xl border border-[#dbe9f7] bg-[#f4f9fe] p-4 text-[10px] leading-5 text-[#4d6d88] sm:mx-8"><strong className="font-semibold text-[#315c7d]">Duplicate handling:</strong> Existing contacts will be updated when the email address matches.</div></div>}

      {step===2&&<div className="p-5 sm:p-8"><div className="text-center"><span className={`mx-auto grid size-12 place-items-center rounded-2xl ${validating?"bg-[#eeedff] text-[#625cf6]":"bg-[#eaf8ef] text-[#3e8d5c]"}`}>{validating?<Loader2 size={21} className="animate-spin"/>:<CheckCircle2 size={22}/>}</span><h2 className="mt-4 text-[18px] font-semibold tracking-[-.025em]">{validating?"Checking your data…":"Ready to import"}</h2><p className="mt-2 text-[11px] text-[var(--text-tertiary)]">{validating?"Validating emails, duplicates and required fields.":"We found 4,701 clean contacts. Review the exceptions below."}</p></div><div className="mx-auto mt-7 max-w-[680px]"><div role="progressbar" aria-label="Contact validation progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} className="h-2 overflow-hidden rounded-full bg-[var(--surface-subtle)]"><div className="h-full rounded-full bg-[#625cf6] transition-[width]" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-[9px] text-[var(--text-tertiary)]"><span>{progress}% complete</span><span>4,821 records</span></div>{progress===100&&<><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["4,701","Ready","success"],["78","Duplicates","info"],["32","Invalid email","danger"],["10","Missing email","warning"]].map(([value,label,tone])=><div key={label} className="rounded-xl border border-[var(--border)] p-4"><p className="text-[20px] font-semibold tracking-[-.035em]">{value}</p><p className="mt-1 text-[9px] text-[var(--text-tertiary)]">{label}</p><span className={`mt-3 inline-flex badge badge-${tone}`}>{tone==="success"?<Check size={9}/>:<AlertTriangle size={9}/>} {tone==="success"?"Import":"Review"}</span></div>)}</div><div className="mt-5 overflow-hidden rounded-xl border border-[var(--border)]"><div className="flex items-center justify-between bg-[var(--surface-subtle)] px-4 py-3"><p className="text-[10px] font-semibold">Exception preview</p><button className="text-[9px] font-semibold text-[#625cf6]">Download report</button></div>{[["alexey@lexbridge","Invalid email format"],["anna@prism.example","Duplicate of existing contact"],["Row 4,776","Missing email address"]].map(row=><div key={row[0]} className="flex justify-between border-t border-[var(--border)] px-4 py-3 text-[9px]"><span className="font-medium">{row[0]}</span><span className="text-[var(--text-tertiary)]">{row[1]}</span></div>)}</div></>}</div></div>}

      {step===3&&<div className="flex min-h-[500px] flex-col items-center justify-center p-8 text-center"><span className="grid size-16 place-items-center rounded-2xl bg-[#eaf8ef] text-[#3e8d5c] shadow-[0_0_0_7px_rgba(69,163,108,.08)]"><Check size={28} strokeWidth={2.5}/></span><p className="section-eyebrow mt-7">Import complete</p><h2 className="mt-2 text-[26px] font-semibold tracking-[-.04em]">4,701 contacts are ready.</h2><p className="mt-3 max-w-md text-[11px] leading-5 text-[var(--text-tertiary)]">Your new contacts were added to the Legal Team workspace. 78 existing records were updated safely.</p><div className="mt-7 flex flex-wrap justify-center gap-2"><Link href="/contacts" className="btn btn-secondary gap-2">View contacts<ArrowRight size={13}/></Link><Link href="/campaigns/new?source=import&count=4701" className="btn btn-primary gap-2">Create campaign<ArrowRight size={13}/></Link></div><button onClick={()=>{setStep(0);setFile("");setProgress(0)}} className="mt-5 flex items-center gap-1.5 text-[10px] font-semibold text-[var(--text-tertiary)]"><RotateCcw size={12}/>Import another file</button></div>}
    </section>
    {step<3&&<div className="flex items-center justify-between"><button onClick={()=>setStep(current=>Math.max(0,current-1))} disabled={step===0} className="btn btn-secondary gap-2"><ArrowLeft size={13}/>Back</button><button onClick={next} disabled={(step===0&&!file)||(step===2&&(validating||progress<100))} className="btn btn-primary gap-2">{step===2?"Import 4,701 contacts":"Continue"}<ArrowRight size={13}/></button></div>}
  </div>;
}
