"use client";

import { BadgeCheck, BellRing, Building2, Check, ChevronRight, CreditCard, Globe2, KeyRound, Mail, Palette, Plug, Plus, Save, ShieldCheck, Trash2, Upload, UserPlus, UsersRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { BRAND_NAME } from "@/config/brand";
import { Switch } from "@/components/ui";

type Section="Workspace"|"Members"|"Sending domains"|"Email senders"|"Brand kit"|"Integrations"|"Billing"|"Security";
const sections:{label:Section;Icon:typeof Building2}[]=[{label:"Workspace",Icon:Building2},{label:"Members",Icon:UsersRound},{label:"Sending domains",Icon:Globe2},{label:"Email senders",Icon:Mail},{label:"Brand kit",Icon:Palette},{label:"Integrations",Icon:Plug},{label:"Billing",Icon:CreditCard},{label:"Security",Icon:ShieldCheck}];

export function SettingsView(){
  const [section,setSection]=useState<Section>("Workspace");
  const [saved,setSaved]=useState(false);
  const saveTimerRef=useRef<number | null>(null);
  useEffect(()=>()=>{
    if(saveTimerRef.current!==null) window.clearTimeout(saveTimerRef.current);
  },[]);
  const save=()=>{
    if(saveTimerRef.current!==null) window.clearTimeout(saveTimerRef.current);
    setSaved(true);
    saveTimerRef.current=window.setTimeout(()=>{setSaved(false);saveTimerRef.current=null},2200);
  };
  return <div className="space-y-6"><div><p className="section-eyebrow">Workspace administration</p><h1 className="mt-2 text-[28px] font-medium tracking-[-.04em]">Settings</h1><p className="mt-1.5 text-sm text-[var(--text-secondary)]">Manage your workspace, sending identity and team.</p></div><div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><nav className="card h-fit p-2" aria-label="Settings sections">{sections.map(({label,Icon})=><button key={label} onClick={()=>setSection(label)} className={`flex w-full items-center gap-2.5 rounded-lg px-3 py-2.5 text-left text-[10px] font-semibold transition-colors ${section===label?"bg-[#eeedff] text-[#5b55d8]":"text-[var(--text-secondary)] hover:bg-[var(--surface-subtle)]"}`}><Icon size={14}/><span className="flex-1">{label}</span>{section===label&&<ChevronRight size={12}/>}</button>)}</nav><section className="card min-h-[640px] overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4 sm:px-6"><div><h2 className="text-[15px] font-semibold">{section}</h2><p className="mt-1 text-[10px] text-[var(--text-tertiary)]">{descriptions[section]}</p></div>{["Workspace","Brand kit"].includes(section)&&<button onClick={save} className="btn btn-primary gap-2">{saved?<Check size={14}/>:<Save size={14}/>} {saved?"Saved":"Save changes"}</button>}</div><div className="p-5 sm:p-6"><SettingsContent section={section}/></div></section></div>{saved&&<div role="status" aria-live="polite" className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl border border-[var(--border)] bg-white px-4 py-3 text-[10px] font-semibold shadow-[var(--shadow-floating)]"><span className="grid size-5 place-items-center rounded-full bg-[#e9f7ef] text-[#3e8d5b]"><Check size={12}/></span>Settings saved</div>}</div>
}

const descriptions:Record<Section,string>={Workspace:"General details and workspace preferences.",Members:"Invite teammates and manage access.","Sending domains":"Authenticate domains for reliable delivery.","Email senders":"Manage the names and addresses your team sends from.","Brand kit":"Keep every email visually consistent.",Integrations:`Connect ${BRAND_NAME} to the tools your team already uses.`,Billing:"Plan, usage and payment details.",Security:"Authentication and workspace protection."};

function SettingsContent({section}:{section:Section}){
  if(section==="Workspace")return <div className="max-w-[620px] space-y-7"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-[#625cf6] text-xl font-semibold text-white">LT</span><div><button className="btn btn-secondary gap-2"><Upload size={13}/>Change logo</button><p className="mt-2 text-[9px] text-[var(--text-tertiary)]">PNG, JPG or SVG · 2 MB max</p></div></div><FormSection title="Workspace details"><div className="grid gap-4 sm:grid-cols-2"><Field label="Workspace name" value="Legal Team"/><Field label="Workspace URL" value="mailflow.work/legal-team"/></div><Field label="Company name" value="Northstar Legal Group"/><Field label="Website" value="https://northstar.legal"/></FormSection><FormSection title="Regional preferences"><div className="grid gap-4 sm:grid-cols-2"><Field label="Timezone" value="Europe/Moscow (UTC+3)"/><Field label="Default language" value="English"/></div></FormSection></div>;
  if(section==="Brand kit")return <div className="max-w-[720px] space-y-7"><div className="grid gap-5 sm:grid-cols-[1fr_190px]"><FormSection title="Brand identity"><Field label="Company name" value="Northstar Legal"/><Field label="Website" value="northstar.legal"/><div><p className="mb-2 text-[10px] font-semibold">Brand colors</p><div className="flex gap-2">{["#242530","#625CF6","#FFFFFF","#F3F4F8"].map(color=><button key={color} aria-label={`Brand color ${color}`} className="size-9 rounded-lg border border-[var(--border)] shadow-sm" style={{backgroundColor:color}}/>) }<button aria-label="Add brand color" className="grid size-9 place-items-center rounded-lg border border-dashed border-[var(--border-strong)] text-[var(--text-tertiary)]"><Plus size={14}/></button></div></div><Field label="Brand font" value="Geist"/></FormSection><div className="rounded-2xl bg-[var(--surface-subtle)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.08em] text-[var(--text-tertiary)]">Logo preview</p><div className="mt-4 grid aspect-square place-items-center rounded-xl bg-white shadow-sm"><div className="text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-[#242530] text-sm font-semibold text-white">N</span><p className="mt-3 text-[9px] font-semibold tracking-[.14em]">NORTHSTAR</p><p className="text-[7px] tracking-[.12em] text-[#625cf6]">LEGAL</p></div></div></div></div><FormSection title="Default email footer"><textarea className="input min-h-28 w-full resize-y py-3 text-[10px] leading-5" defaultValue={"Northstar Legal Group\n18 Tverskaya Street, Moscow 125009\nYou received this email because you have a professional relationship with our team."}/></FormSection></div>;
  if(section==="Members")return <div><div className="flex items-center justify-between"><div><h3 className="text-[13px] font-semibold">Workspace members</h3><p className="mt-1 text-[10px] text-[var(--text-tertiary)]">4 of 10 seats used</p></div><button className="btn btn-primary gap-2"><UserPlus size={13}/>Invite member</button></div><div className="mt-5 overflow-hidden rounded-xl border border-[var(--border)]">{[["Egor Sabalin","egor@northstar.legal","Workspace Admin","ES","#625cf6"],["Alina Volkova","alina@northstar.legal","Editor","AV","#2f8a79"],["Elena Morozova","elena@northstar.legal","Editor","EM","#d97757"],["Pavel Romanov","pavel@northstar.legal","Viewer","PR","#3b82c4"]].map(member=><div key={member[1]} className="flex items-center gap-3 border-b border-[var(--border)] p-4 last:border-0"><span className="grid size-9 place-items-center rounded-full text-[9px] font-semibold text-white" style={{backgroundColor:member[4]}}>{member[3]}</span><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold">{member[0]}</p><p className="mt-0.5 truncate text-[8px] text-[var(--text-tertiary)]">{member[1]}</p></div><span className="badge badge-neutral">{member[2]}</span><button className="text-[var(--text-tertiary)]" aria-label={`Remove ${member[0]}`}><Trash2 size={14}/></button></div>)}</div></div>;
  if(section==="Sending domains")return <div><div className="flex items-center justify-between"><div><h3 className="text-[13px] font-semibold">Authenticated domains</h3><p className="mt-1 text-[10px] text-[var(--text-tertiary)]">SPF, DKIM and DMARC protect your reputation.</p></div><button className="btn btn-primary gap-2"><Plus size={13}/>Add domain</button></div><div className="mt-5 space-y-3">{[["northstar.legal","Verified","success","All records configured"],["events.northstar.legal","Pending","warning","DKIM record missing"]].map(item=><div key={item[0]} className="flex items-center gap-4 rounded-xl border border-[var(--border)] p-4"><span className={`grid size-10 place-items-center rounded-xl ${item[2]==="success"?"bg-[#e9f7ef] text-[#3e8d5b]":"bg-[#fff5df] text-[#a9640a]"}`}><Globe2 size={17}/></span><div className="flex-1"><p className="text-[11px] font-semibold">{item[0]}</p><p className="mt-1 text-[9px] text-[var(--text-tertiary)]">{item[3]}</p></div><span className={`badge badge-${item[2]}`}>{item[2]==="success"&&<Check size={9}/>} {item[1]}</span></div>)}</div></div>;
  if(section==="Email senders")return <div><div className="flex items-center justify-between"><h3 className="text-[13px] font-semibold">Verified senders</h3><button className="btn btn-primary gap-2"><Plus size={13}/>Add sender</button></div><div className="mt-5 space-y-3">{[["Egor Sabalin","egor@northstar.legal","Default sender"],["Northstar Events","events@northstar.legal","Campaign sender"],["Partner Relations","partners@northstar.legal","Campaign sender"]].map((item,index)=><div key={item[1]} className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-4"><span className="grid size-9 place-items-center rounded-full bg-[#eeedff] text-[9px] font-semibold text-[#625cf6]">{item[0].split(" ").map(v=>v[0]).join("")}</span><div className="flex-1"><p className="text-[10px] font-semibold">{item[0]}</p><p className="text-[8px] text-[var(--text-tertiary)]">{item[1]}</p></div><span className="badge badge-success"><BadgeCheck size={9}/>{index===0?"Default":"Verified"}</span></div>)}</div></div>;
  if(section==="Integrations")return <div><h3 className="text-[13px] font-semibold">Available integrations</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Google Sheets","Sync contacts from shared sheets","G","#2f9d59",true],["Salesforce","Keep contacts and activity aligned","S","#2493d1",false],["HubSpot","Sync CRM records and owners","H","#ef7a45",false],["Zapier","Connect to thousands of tools","Z","#ff6b35",true]].map(item=><div key={item[0] as string} className="rounded-xl border border-[var(--border)] p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg text-sm font-bold text-white" style={{backgroundColor:item[3] as string}}>{item[2] as string}</span><div className="flex-1"><p className="text-[11px] font-semibold">{item[0] as string}</p><p className="text-[9px] text-[var(--text-tertiary)]">{item[1] as string}</p></div></div><button className={`mt-4 btn w-full ${(item[4] as boolean)?"btn-secondary":"btn-primary"}`}>{(item[4] as boolean)?"Manage":"Connect"}</button></div>)}</div></div>;
  if(section==="Billing")return <div><div className="rounded-2xl bg-[#242530] p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span className="badge !border-white/10 !bg-white/10 !text-white">Growth plan</span><p className="mt-4 text-[28px] font-semibold tracking-[-.04em]">$149 <span className="text-[12px] font-normal text-white/50">/ month</span></p><p className="mt-2 text-[10px] text-white/55">Up to 50,000 contacts and 250,000 monthly emails.</p></div><button className="btn bg-white text-[#242530]">Manage plan</button></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[49%] rounded-full bg-[#817bf4]"/></div><div className="mt-2 flex justify-between text-[9px] text-white/50"><span>24,821 / 50,000 contacts</span><span>49%</span></div></div><FormSection title="Payment method"><div className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-4"><span className="grid size-10 place-items-center rounded-lg bg-[var(--surface-subtle)]"><CreditCard size={17}/></span><div className="flex-1"><p className="text-[10px] font-semibold">Visa ending in 4242</p><p className="text-[8px] text-[var(--text-tertiary)]">Expires 08/29</p></div><button className="btn btn-secondary">Update</button></div></FormSection></div>;
  return <div className="max-w-[700px] space-y-6"><FormSection title="Authentication"><SettingRow Icon={KeyRound} title="Two-factor authentication" copy="Require a second factor when signing in." action={<button className="btn btn-secondary">Configure</button>}/><SettingRow Icon={ShieldCheck} title="Single sign-on" copy="Connect your identity provider via SAML." action={<button className="btn btn-secondary">Set up SSO</button>}/></FormSection><FormSection title="Session controls"><SettingRow Icon={BellRing} title="Login alerts" copy="Notify admins about sign-ins from a new device." action={<Switch defaultChecked label="Enable login alerts"/>}/><SettingRow Icon={KeyRound} title="Session duration" copy="Automatically sign members out after 30 days." action={<button className="btn btn-secondary">30 days</button>}/></FormSection></div>;
}

function Field({label,value}:{label:string;value:string}){return <label className="block"><span className="mb-1.5 block text-[10px] font-semibold">{label}</span><input className="input h-10 w-full text-[11px]" defaultValue={value}/></label>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4"><h3 className="text-[12px] font-semibold">{title}</h3>{children}</section>}
function SettingRow({Icon,title,copy,action}:{Icon:typeof KeyRound;title:string;copy:string;action:React.ReactNode}){return <div className="flex items-center gap-4 rounded-xl border border-[var(--border)] p-4"><span className="grid size-9 place-items-center rounded-lg bg-[var(--surface-subtle)] text-[var(--text-secondary)]"><Icon size={15}/></span><div className="flex-1"><p className="text-[10px] font-semibold">{title}</p><p className="mt-1 text-[8px] text-[var(--text-tertiary)]">{copy}</p></div>{action}</div>}
